2015-07-27 13:27:23,712 a9452a02 MainThread pkb.py:336 INFO     Flag values:
--machine_type=Standard_D2
--cloud=Azure
--benchmarks=object_storage_service
2015-07-27 13:27:23,776 a9452a02 MainThread publisher.py:501 DEBUG    Using publishers: [<LogPublisher logger=<logging.RootLogger object at 0x7f4f81b6d990> level=20>, <PrettyPrintStreamPublisher stream=<open file '<stdout>', mode 'w' at 0x7f4f8366c150>>, <NewlineDelimitedJSONPublisher file_path="/tmp/perfkitbenchmarker/run_a9452a02/perfkitbenchmarker_results.json" mode="wb">]
2015-07-27 13:27:23,776 a9452a02 MainThread object_storage_service(1/1) __init__.py:91 WARNING  File resource loader root data is not a directory.
2015-07-27 13:27:23,777 a9452a02 MainThread object_storage_service(1/1) pkb.py:194 INFO     Preparing benchmark object_storage_service
2015-07-27 13:27:23,779 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:27:23,780 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure account affinity-group create --location=East US --label=perfkita9452a02de3514208 perfkita9452a02de3514208
2015-07-27 13:27:26,930 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure account affinity-group create --location=East US --label=perfkita9452a02de3514208 perfkita9452a02de3514208. Got return code (0).
STDOUT: info:    Executing command account affinity-group create
info:    Creating affinity group
info:    account affinity-group create command OK

STDERR: 
2015-07-27 13:27:26,930 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:27:26,930 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure account affinity-group show --json perfkita9452a02de3514208
2015-07-27 13:27:29,795 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure account affinity-group show --json perfkita9452a02de3514208. Got return code (0).
STDOUT: {
  "capabilities": [
    "PersistentVMRole",
    "HighMemory"
  ],
  "hostedServices": [],
  "storageServices": [],
  "name": "perfkita9452a02de3514208",
  "label": "perfkita9452a02de3514208",
  "location": "East US",
  "createdTime": "2015-07-27T13:27:43.000Z",
  "statusCode": 200,
  "requestId": "179c1f8ad418c8668e43c388e03ee64b"
}

STDERR: 
2015-07-27 13:27:29,796 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:27:29,796 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208
2015-07-27 13:27:43,017 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:418 INFO     Ran azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208. Got return code (1).
STDOUT: info:    Executing command storage account create
info:    Creating storage account
info:    Error information has been recorded to /root/.azure/azure.err

STDERR: error:   The subscription policy limit for resource type 'storage account count' was exceeded. The limit for resource type 'storage account count' is 100 per subscription, the current count is 100, and the requested increment is 1.
error:   storage account create command failed


2015-07-27 13:27:43,018 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:27:43,018 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account show --json perfkita9452a02de3514208
2015-07-27 13:27:45,975 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure storage account show --json perfkita9452a02de3514208. Got return code (1).
STDOUT: 
STDERR: The storage account 'perfkita9452a02de3514208' was not found.
Error information has been recorded to /root/.azure/azure.err
storage account show command failed


2015-07-27 13:27:45,976 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _CreateResource: Creation of AzureStorageAccount failed.
2015-07-27 13:28:06,033 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:28:06,033 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208
2015-07-27 13:28:17,685 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:418 INFO     Ran azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208. Got return code (1).
STDOUT: info:    Executing command storage account create
info:    Creating storage account
info:    Error information has been recorded to /root/.azure/azure.err

STDERR: error:   The subscription policy limit for resource type 'storage account count' was exceeded. The limit for resource type 'storage account count' is 100 per subscription, the current count is 100, and the requested increment is 1.
error:   storage account create command failed


2015-07-27 13:28:17,686 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:28:17,686 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account show --json perfkita9452a02de3514208
2015-07-27 13:28:20,558 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure storage account show --json perfkita9452a02de3514208. Got return code (1).
STDOUT: 
STDERR: The storage account 'perfkita9452a02de3514208' was not found.
Error information has been recorded to /root/.azure/azure.err
storage account show command failed


2015-07-27 13:28:20,558 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _CreateResource: Creation of AzureStorageAccount failed.
2015-07-27 13:28:41,198 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:28:41,198 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208
2015-07-27 13:28:52,390 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:418 INFO     Ran azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208. Got return code (1).
STDOUT: info:    Executing command storage account create
info:    Creating storage account
info:    Error information has been recorded to /root/.azure/azure.err

STDERR: error:   The subscription policy limit for resource type 'storage account count' was exceeded. The limit for resource type 'storage account count' is 100 per subscription, the current count is 100, and the requested increment is 1.
error:   storage account create command failed


2015-07-27 13:28:52,391 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:28:52,391 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account show --json perfkita9452a02de3514208
2015-07-27 13:28:55,226 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure storage account show --json perfkita9452a02de3514208. Got return code (1).
STDOUT: 
STDERR: The storage account 'perfkita9452a02de3514208' was not found.
Error information has been recorded to /root/.azure/azure.err
storage account show command failed


2015-07-27 13:28:55,227 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _CreateResource: Creation of AzureStorageAccount failed.
2015-07-27 13:29:17,560 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:29:17,560 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208
2015-07-27 13:29:35,633 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:418 INFO     Ran azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208. Got return code (1).
STDOUT: info:    Executing command storage account create
info:    Creating storage account
info:    Error information has been recorded to /root/.azure/azure.err

STDERR: error:   The subscription policy limit for resource type 'storage account count' was exceeded. The limit for resource type 'storage account count' is 100 per subscription, the current count is 100, and the requested increment is 1.
error:   storage account create command failed


2015-07-27 13:29:35,634 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:29:35,634 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account show --json perfkita9452a02de3514208
2015-07-27 13:29:38,351 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure storage account show --json perfkita9452a02de3514208. Got return code (1).
STDOUT: 
STDERR: The storage account 'perfkita9452a02de3514208' was not found.
Error information has been recorded to /root/.azure/azure.err
storage account show command failed


2015-07-27 13:29:38,351 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _CreateResource: Creation of AzureStorageAccount failed.
2015-07-27 13:29:54,161 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:29:54,161 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208
2015-07-27 13:30:05,532 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:418 INFO     Ran azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208. Got return code (1).
STDOUT: info:    Executing command storage account create
info:    Creating storage account
info:    Error information has been recorded to /root/.azure/azure.err

STDERR: error:   The subscription policy limit for resource type 'storage account count' was exceeded. The limit for resource type 'storage account count' is 100 per subscription, the current count is 100, and the requested increment is 1.
error:   storage account create command failed


2015-07-27 13:30:05,533 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:30:05,533 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account show --json perfkita9452a02de3514208
2015-07-27 13:30:08,385 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure storage account show --json perfkita9452a02de3514208. Got return code (1).
STDOUT: 
STDERR: The storage account 'perfkita9452a02de3514208' was not found.
Error information has been recorded to /root/.azure/azure.err
storage account show command failed


2015-07-27 13:30:08,386 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _CreateResource: Creation of AzureStorageAccount failed.
2015-07-27 13:30:37,970 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:30:37,970 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208
2015-07-27 13:30:49,733 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:418 INFO     Ran azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208. Got return code (1).
STDOUT: info:    Executing command storage account create
info:    Creating storage account
info:    Error information has been recorded to /root/.azure/azure.err

STDERR: error:   The subscription policy limit for resource type 'storage account count' was exceeded. The limit for resource type 'storage account count' is 100 per subscription, the current count is 100, and the requested increment is 1.
error:   storage account create command failed


2015-07-27 13:30:49,733 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:30:49,734 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account show --json perfkita9452a02de3514208
2015-07-27 13:30:52,799 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure storage account show --json perfkita9452a02de3514208. Got return code (1).
STDOUT: 
STDERR: The storage account 'perfkita9452a02de3514208' was not found.
Error information has been recorded to /root/.azure/azure.err
storage account show command failed


2015-07-27 13:30:52,800 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _CreateResource: Creation of AzureStorageAccount failed.
2015-07-27 13:31:16,153 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:31:16,154 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208
2015-07-27 13:31:27,198 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:418 INFO     Ran azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208. Got return code (1).
STDOUT: info:    Executing command storage account create
info:    Creating storage account
info:    Error information has been recorded to /root/.azure/azure.err

STDERR: error:   The subscription policy limit for resource type 'storage account count' was exceeded. The limit for resource type 'storage account count' is 100 per subscription, the current count is 100, and the requested increment is 1.
error:   storage account create command failed


2015-07-27 13:31:27,200 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:31:27,200 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account show --json perfkita9452a02de3514208
2015-07-27 13:31:29,926 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure storage account show --json perfkita9452a02de3514208. Got return code (1).
STDOUT: 
STDERR: The storage account 'perfkita9452a02de3514208' was not found.
Error information has been recorded to /root/.azure/azure.err
storage account show command failed


2015-07-27 13:31:29,926 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _CreateResource: Creation of AzureStorageAccount failed.
2015-07-27 13:31:57,888 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:31:57,889 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208
2015-07-27 13:32:13,186 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:418 INFO     Ran azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208. Got return code (1).
STDOUT: info:    Executing command storage account create
info:    Creating storage account
info:    Error information has been recorded to /root/.azure/azure.err

STDERR: error:   The subscription policy limit for resource type 'storage account count' was exceeded. The limit for resource type 'storage account count' is 100 per subscription, the current count is 100, and the requested increment is 1.
error:   storage account create command failed


2015-07-27 13:32:13,187 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:32:13,187 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account show --json perfkita9452a02de3514208
2015-07-27 13:32:16,619 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure storage account show --json perfkita9452a02de3514208. Got return code (1).
STDOUT: 
STDERR: The storage account 'perfkita9452a02de3514208' was not found.
Error information has been recorded to /root/.azure/azure.err
storage account show command failed


2015-07-27 13:32:16,619 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _CreateResource: Creation of AzureStorageAccount failed.
2015-07-27 13:32:43,704 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:32:43,705 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208
2015-07-27 13:32:55,252 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:418 INFO     Ran azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208. Got return code (1).
STDOUT: info:    Executing command storage account create
info:    Creating storage account
info:    Error information has been recorded to /root/.azure/azure.err

STDERR: error:   The subscription policy limit for resource type 'storage account count' was exceeded. The limit for resource type 'storage account count' is 100 per subscription, the current count is 100, and the requested increment is 1.
error:   storage account create command failed


2015-07-27 13:32:55,253 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:32:55,253 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account show --json perfkita9452a02de3514208
2015-07-27 13:32:58,642 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure storage account show --json perfkita9452a02de3514208. Got return code (1).
STDOUT: 
STDERR: The storage account 'perfkita9452a02de3514208' was not found.
Error information has been recorded to /root/.azure/azure.err
storage account show command failed


2015-07-27 13:32:58,643 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _CreateResource: Creation of AzureStorageAccount failed.
2015-07-27 13:33:21,566 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:33:21,566 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208
2015-07-27 13:33:33,386 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:418 INFO     Ran azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208. Got return code (1).
STDOUT: info:    Executing command storage account create
info:    Creating storage account
info:    Error information has been recorded to /root/.azure/azure.err

STDERR: error:   The subscription policy limit for resource type 'storage account count' was exceeded. The limit for resource type 'storage account count' is 100 per subscription, the current count is 100, and the requested increment is 1.
error:   storage account create command failed


2015-07-27 13:33:33,387 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:33:33,387 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account show --json perfkita9452a02de3514208
2015-07-27 13:33:36,377 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure storage account show --json perfkita9452a02de3514208. Got return code (1).
STDOUT: 
STDERR: The storage account 'perfkita9452a02de3514208' was not found.
Error information has been recorded to /root/.azure/azure.err
storage account show command failed


2015-07-27 13:33:36,377 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _CreateResource: Creation of AzureStorageAccount failed.
2015-07-27 13:34:00,159 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:34:00,159 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208
2015-07-27 13:34:11,884 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:418 INFO     Ran azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208. Got return code (1).
STDOUT: info:    Executing command storage account create
info:    Creating storage account
info:    Error information has been recorded to /root/.azure/azure.err

STDERR: error:   The subscription policy limit for resource type 'storage account count' was exceeded. The limit for resource type 'storage account count' is 100 per subscription, the current count is 100, and the requested increment is 1.
error:   storage account create command failed


2015-07-27 13:34:11,885 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:34:11,885 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account show --json perfkita9452a02de3514208
2015-07-27 13:34:14,814 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure storage account show --json perfkita9452a02de3514208. Got return code (1).
STDOUT: 
STDERR: The storage account 'perfkita9452a02de3514208' was not found.
Error information has been recorded to /root/.azure/azure.err
storage account show command failed


2015-07-27 13:34:14,814 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _CreateResource: Creation of AzureStorageAccount failed.
2015-07-27 13:34:39,407 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:34:39,407 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208
2015-07-27 13:34:51,349 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:418 INFO     Ran azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208. Got return code (1).
STDOUT: info:    Executing command storage account create
info:    Creating storage account
info:    Error information has been recorded to /root/.azure/azure.err

STDERR: error:   The subscription policy limit for resource type 'storage account count' was exceeded. The limit for resource type 'storage account count' is 100 per subscription, the current count is 100, and the requested increment is 1.
error:   storage account create command failed


2015-07-27 13:34:51,350 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:34:51,350 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account show --json perfkita9452a02de3514208
2015-07-27 13:34:54,350 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure storage account show --json perfkita9452a02de3514208. Got return code (1).
STDOUT: 
STDERR: The storage account 'perfkita9452a02de3514208' was not found.
Error information has been recorded to /root/.azure/azure.err
storage account show command failed


2015-07-27 13:34:54,350 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _CreateResource: Creation of AzureStorageAccount failed.
2015-07-27 13:35:12,936 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:35:12,936 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208
2015-07-27 13:35:24,809 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:418 INFO     Ran azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208. Got return code (1).
STDOUT: info:    Executing command storage account create
info:    Creating storage account
info:    Error information has been recorded to /root/.azure/azure.err

STDERR: error:   The subscription policy limit for resource type 'storage account count' was exceeded. The limit for resource type 'storage account count' is 100 per subscription, the current count is 100, and the requested increment is 1.
error:   storage account create command failed


2015-07-27 13:35:24,810 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:35:24,810 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account show --json perfkita9452a02de3514208
2015-07-27 13:35:27,771 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure storage account show --json perfkita9452a02de3514208. Got return code (1).
STDOUT: 
STDERR: The storage account 'perfkita9452a02de3514208' was not found.
Error information has been recorded to /root/.azure/azure.err
storage account show command failed


2015-07-27 13:35:27,771 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _CreateResource: Creation of AzureStorageAccount failed.
2015-07-27 13:35:45,629 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:35:45,629 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208
2015-07-27 13:36:01,278 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:418 INFO     Ran azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208. Got return code (1).
STDOUT: info:    Executing command storage account create
info:    Creating storage account
info:    Error information has been recorded to /root/.azure/azure.err

STDERR: error:   The subscription policy limit for resource type 'storage account count' was exceeded. The limit for resource type 'storage account count' is 100 per subscription, the current count is 100, and the requested increment is 1.
error:   storage account create command failed


2015-07-27 13:36:01,279 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:36:01,279 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account show --json perfkita9452a02de3514208
2015-07-27 13:36:04,247 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure storage account show --json perfkita9452a02de3514208. Got return code (1).
STDOUT: 
STDERR: The storage account 'perfkita9452a02de3514208' was not found.
Error information has been recorded to /root/.azure/azure.err
storage account show command failed


2015-07-27 13:36:04,247 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _CreateResource: Creation of AzureStorageAccount failed.
2015-07-27 13:36:30,078 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:36:30,078 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208
2015-07-27 13:36:41,867 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:418 INFO     Ran azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208. Got return code (1).
STDOUT: info:    Executing command storage account create
info:    Creating storage account
info:    Error information has been recorded to /root/.azure/azure.err

STDERR: error:   The subscription policy limit for resource type 'storage account count' was exceeded. The limit for resource type 'storage account count' is 100 per subscription, the current count is 100, and the requested increment is 1.
error:   storage account create command failed


2015-07-27 13:36:41,869 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:36:41,869 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account show --json perfkita9452a02de3514208
2015-07-27 13:36:45,040 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure storage account show --json perfkita9452a02de3514208. Got return code (1).
STDOUT: 
STDERR: The storage account 'perfkita9452a02de3514208' was not found.
Error information has been recorded to /root/.azure/azure.err
storage account show command failed


2015-07-27 13:36:45,041 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _CreateResource: Creation of AzureStorageAccount failed.
2015-07-27 13:37:11,013 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:37:11,013 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208
2015-07-27 13:37:21,758 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:418 INFO     Ran azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208. Got return code (1).
STDOUT: info:    Executing command storage account create
info:    Creating storage account
info:    Error information has been recorded to /root/.azure/azure.err

STDERR: error:   The subscription policy limit for resource type 'storage account count' was exceeded. The limit for resource type 'storage account count' is 100 per subscription, the current count is 100, and the requested increment is 1.
error:   storage account create command failed


2015-07-27 13:37:21,758 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:37:21,758 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account show --json perfkita9452a02de3514208
2015-07-27 13:37:24,726 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure storage account show --json perfkita9452a02de3514208. Got return code (1).
STDOUT: 
STDERR: The storage account 'perfkita9452a02de3514208' was not found.
Error information has been recorded to /root/.azure/azure.err
storage account show command failed


2015-07-27 13:37:24,727 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _CreateResource: Creation of AzureStorageAccount failed.
2015-07-27 13:37:53,266 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:37:53,267 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208
2015-07-27 13:38:04,512 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:418 INFO     Ran azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208. Got return code (1).
STDOUT: info:    Executing command storage account create
info:    Creating storage account
info:    Error information has been recorded to /root/.azure/azure.err

STDERR: error:   The subscription policy limit for resource type 'storage account count' was exceeded. The limit for resource type 'storage account count' is 100 per subscription, the current count is 100, and the requested increment is 1.
error:   storage account create command failed


2015-07-27 13:38:04,513 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:38:04,513 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account show --json perfkita9452a02de3514208
2015-07-27 13:38:07,453 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure storage account show --json perfkita9452a02de3514208. Got return code (1).
STDOUT: 
STDERR: The storage account 'perfkita9452a02de3514208' was not found.
Error information has been recorded to /root/.azure/azure.err
storage account show command failed


2015-07-27 13:38:07,454 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _CreateResource: Creation of AzureStorageAccount failed.
2015-07-27 13:38:30,684 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:38:30,684 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208
2015-07-27 13:38:45,282 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:418 INFO     Ran azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208. Got return code (1).
STDOUT: info:    Executing command storage account create
info:    Creating storage account
info:    Error information has been recorded to /root/.azure/azure.err

STDERR: error:   The subscription policy limit for resource type 'storage account count' was exceeded. The limit for resource type 'storage account count' is 100 per subscription, the current count is 100, and the requested increment is 1.
error:   storage account create command failed


2015-07-27 13:38:45,284 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:38:45,284 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account show --json perfkita9452a02de3514208
2015-07-27 13:38:48,125 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure storage account show --json perfkita9452a02de3514208. Got return code (1).
STDOUT: 
STDERR: The storage account 'perfkita9452a02de3514208' was not found.
Error information has been recorded to /root/.azure/azure.err
storage account show command failed


2015-07-27 13:38:48,126 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _CreateResource: Creation of AzureStorageAccount failed.
2015-07-27 13:39:15,702 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:39:15,702 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208
2015-07-27 13:39:26,016 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:418 INFO     Ran azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208. Got return code (1).
STDOUT: info:    Executing command storage account create
info:    Creating storage account
info:    Error information has been recorded to /root/.azure/azure.err

STDERR: error:   The subscription policy limit for resource type 'storage account count' was exceeded. The limit for resource type 'storage account count' is 100 per subscription, the current count is 100, and the requested increment is 1.
error:   storage account create command failed


2015-07-27 13:39:26,017 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:39:26,017 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account show --json perfkita9452a02de3514208
2015-07-27 13:39:28,782 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure storage account show --json perfkita9452a02de3514208. Got return code (1).
STDOUT: 
STDERR: The storage account 'perfkita9452a02de3514208' was not found.
Error information has been recorded to /root/.azure/azure.err
storage account show command failed


2015-07-27 13:39:28,782 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _CreateResource: Creation of AzureStorageAccount failed.
2015-07-27 13:39:54,646 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:39:54,647 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208
2015-07-27 13:40:05,077 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:418 INFO     Ran azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208. Got return code (1).
STDOUT: info:    Executing command storage account create
info:    Creating storage account
info:    Error information has been recorded to /root/.azure/azure.err

STDERR: error:   The subscription policy limit for resource type 'storage account count' was exceeded. The limit for resource type 'storage account count' is 100 per subscription, the current count is 100, and the requested increment is 1.
error:   storage account create command failed


2015-07-27 13:40:05,078 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:40:05,078 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account show --json perfkita9452a02de3514208
2015-07-27 13:40:07,949 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure storage account show --json perfkita9452a02de3514208. Got return code (1).
STDOUT: 
STDERR: The storage account 'perfkita9452a02de3514208' was not found.
Error information has been recorded to /root/.azure/azure.err
storage account show command failed


2015-07-27 13:40:07,949 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _CreateResource: Creation of AzureStorageAccount failed.
2015-07-27 13:40:34,160 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:40:34,160 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208
2015-07-27 13:40:48,217 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:418 INFO     Ran azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208. Got return code (1).
STDOUT: info:    Executing command storage account create
info:    Creating storage account
info:    Error information has been recorded to /root/.azure/azure.err

STDERR: error:   The subscription policy limit for resource type 'storage account count' was exceeded. The limit for resource type 'storage account count' is 100 per subscription, the current count is 100, and the requested increment is 1.
error:   storage account create command failed


2015-07-27 13:40:48,219 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:40:48,219 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account show --json perfkita9452a02de3514208
2015-07-27 13:40:51,471 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure storage account show --json perfkita9452a02de3514208. Got return code (1).
STDOUT: 
STDERR: The storage account 'perfkita9452a02de3514208' was not found.
Error information has been recorded to /root/.azure/azure.err
storage account show command failed


2015-07-27 13:40:51,472 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _CreateResource: Creation of AzureStorageAccount failed.
2015-07-27 13:41:11,624 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:41:11,624 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208
2015-07-27 13:41:22,044 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:418 INFO     Ran azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208. Got return code (1).
STDOUT: info:    Executing command storage account create
info:    Creating storage account
info:    Error information has been recorded to /root/.azure/azure.err

STDERR: error:   The subscription policy limit for resource type 'storage account count' was exceeded. The limit for resource type 'storage account count' is 100 per subscription, the current count is 100, and the requested increment is 1.
error:   storage account create command failed


2015-07-27 13:41:22,045 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:41:22,045 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account show --json perfkita9452a02de3514208
2015-07-27 13:41:25,461 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure storage account show --json perfkita9452a02de3514208. Got return code (1).
STDOUT: 
STDERR: The storage account 'perfkita9452a02de3514208' was not found.
Error information has been recorded to /root/.azure/azure.err
storage account show command failed


2015-07-27 13:41:25,462 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _CreateResource: Creation of AzureStorageAccount failed.
2015-07-27 13:41:46,150 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:41:46,150 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208
2015-07-27 13:41:57,467 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:418 INFO     Ran azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208. Got return code (1).
STDOUT: info:    Executing command storage account create
info:    Creating storage account
info:    Error information has been recorded to /root/.azure/azure.err

STDERR: error:   The subscription policy limit for resource type 'storage account count' was exceeded. The limit for resource type 'storage account count' is 100 per subscription, the current count is 100, and the requested increment is 1.
error:   storage account create command failed


2015-07-27 13:41:57,469 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:41:57,469 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account show --json perfkita9452a02de3514208
2015-07-27 13:42:00,143 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure storage account show --json perfkita9452a02de3514208. Got return code (1).
STDOUT: 
STDERR: The storage account 'perfkita9452a02de3514208' was not found.
Error information has been recorded to /root/.azure/azure.err
storage account show command failed


2015-07-27 13:42:00,143 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _CreateResource: Creation of AzureStorageAccount failed.
2015-07-27 13:42:29,869 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:42:29,870 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208
2015-07-27 13:42:41,632 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:418 INFO     Ran azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208. Got return code (1).
STDOUT: info:    Executing command storage account create
info:    Creating storage account
info:    Error information has been recorded to /root/.azure/azure.err

STDERR: error:   The subscription policy limit for resource type 'storage account count' was exceeded. The limit for resource type 'storage account count' is 100 per subscription, the current count is 100, and the requested increment is 1.
error:   storage account create command failed


2015-07-27 13:42:41,633 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:42:41,633 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account show --json perfkita9452a02de3514208
2015-07-27 13:42:44,417 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure storage account show --json perfkita9452a02de3514208. Got return code (1).
STDOUT: 
STDERR: The storage account 'perfkita9452a02de3514208' was not found.
Error information has been recorded to /root/.azure/azure.err
storage account show command failed


2015-07-27 13:42:44,417 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _CreateResource: Creation of AzureStorageAccount failed.
2015-07-27 13:42:59,503 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:42:59,504 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208
2015-07-27 13:43:24,877 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:418 INFO     Ran azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208. Got return code (1).
STDOUT: info:    Executing command storage account create
info:    Creating storage account
info:    Error information has been recorded to /root/.azure/azure.err

STDERR: error:   The subscription policy limit for resource type 'storage account count' was exceeded. The limit for resource type 'storage account count' is 100 per subscription, the current count is 100, and the requested increment is 1.
error:   storage account create command failed


2015-07-27 13:43:24,878 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:43:24,878 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account show --json perfkita9452a02de3514208
2015-07-27 13:43:27,784 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure storage account show --json perfkita9452a02de3514208. Got return code (1).
STDOUT: 
STDERR: The storage account 'perfkita9452a02de3514208' was not found.
Error information has been recorded to /root/.azure/azure.err
storage account show command failed


2015-07-27 13:43:27,784 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _CreateResource: Creation of AzureStorageAccount failed.
2015-07-27 13:43:46,159 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:43:46,160 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208
2015-07-27 13:43:57,692 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:418 INFO     Ran azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208. Got return code (1).
STDOUT: info:    Executing command storage account create
info:    Creating storage account
info:    Error information has been recorded to /root/.azure/azure.err

STDERR: error:   The subscription policy limit for resource type 'storage account count' was exceeded. The limit for resource type 'storage account count' is 100 per subscription, the current count is 100, and the requested increment is 1.
error:   storage account create command failed


2015-07-27 13:43:57,694 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:43:57,694 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account show --json perfkita9452a02de3514208
2015-07-27 13:44:00,513 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure storage account show --json perfkita9452a02de3514208. Got return code (1).
STDOUT: 
STDERR: The storage account 'perfkita9452a02de3514208' was not found.
Error information has been recorded to /root/.azure/azure.err
storage account show command failed


2015-07-27 13:44:00,514 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _CreateResource: Creation of AzureStorageAccount failed.
2015-07-27 13:44:25,001 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:44:25,001 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208
2015-07-27 13:44:36,702 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:418 INFO     Ran azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208. Got return code (1).
STDOUT: info:    Executing command storage account create
info:    Creating storage account
info:    Error information has been recorded to /root/.azure/azure.err

STDERR: error:   The subscription policy limit for resource type 'storage account count' was exceeded. The limit for resource type 'storage account count' is 100 per subscription, the current count is 100, and the requested increment is 1.
error:   storage account create command failed


2015-07-27 13:44:36,703 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:44:36,703 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account show --json perfkita9452a02de3514208
2015-07-27 13:44:39,863 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure storage account show --json perfkita9452a02de3514208. Got return code (1).
STDOUT: 
STDERR: The storage account 'perfkita9452a02de3514208' was not found.
Error information has been recorded to /root/.azure/azure.err
storage account show command failed


2015-07-27 13:44:39,863 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _CreateResource: Creation of AzureStorageAccount failed.
2015-07-27 13:45:00,804 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:45:00,805 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208
2015-07-27 13:45:13,727 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:418 INFO     Ran azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208. Got return code (1).
STDOUT: info:    Executing command storage account create
info:    Creating storage account
info:    Error information has been recorded to /root/.azure/azure.err

STDERR: error:   The subscription policy limit for resource type 'storage account count' was exceeded. The limit for resource type 'storage account count' is 100 per subscription, the current count is 100, and the requested increment is 1.
error:   storage account create command failed


2015-07-27 13:45:13,728 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:45:13,728 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account show --json perfkita9452a02de3514208
2015-07-27 13:45:16,388 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure storage account show --json perfkita9452a02de3514208. Got return code (1).
STDOUT: 
STDERR: The storage account 'perfkita9452a02de3514208' was not found.
Error information has been recorded to /root/.azure/azure.err
storage account show command failed


2015-07-27 13:45:16,389 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _CreateResource: Creation of AzureStorageAccount failed.
2015-07-27 13:45:43,721 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:45:43,721 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208
2015-07-27 13:45:54,775 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:418 INFO     Ran azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208. Got return code (1).
STDOUT: info:    Executing command storage account create
info:    Creating storage account
info:    Error information has been recorded to /root/.azure/azure.err

STDERR: error:   The subscription policy limit for resource type 'storage account count' was exceeded. The limit for resource type 'storage account count' is 100 per subscription, the current count is 100, and the requested increment is 1.
error:   storage account create command failed


2015-07-27 13:45:54,776 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:45:54,776 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account show --json perfkita9452a02de3514208
2015-07-27 13:45:57,674 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure storage account show --json perfkita9452a02de3514208. Got return code (1).
STDOUT: 
STDERR: The storage account 'perfkita9452a02de3514208' was not found.
Error information has been recorded to /root/.azure/azure.err
storage account show command failed


2015-07-27 13:45:57,675 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _CreateResource: Creation of AzureStorageAccount failed.
2015-07-27 13:46:21,227 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:46:21,227 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208
2015-07-27 13:46:33,615 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:418 INFO     Ran azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208. Got return code (1).
STDOUT: info:    Executing command storage account create
info:    Creating storage account
info:    Error information has been recorded to /root/.azure/azure.err

STDERR: error:   The subscription policy limit for resource type 'storage account count' was exceeded. The limit for resource type 'storage account count' is 100 per subscription, the current count is 100, and the requested increment is 1.
error:   storage account create command failed


2015-07-27 13:46:33,616 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:46:33,616 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account show --json perfkita9452a02de3514208
2015-07-27 13:46:37,000 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure storage account show --json perfkita9452a02de3514208. Got return code (1).
STDOUT: 
STDERR: The storage account 'perfkita9452a02de3514208' was not found.
Error information has been recorded to /root/.azure/azure.err
storage account show command failed


2015-07-27 13:46:37,001 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _CreateResource: Creation of AzureStorageAccount failed.
2015-07-27 13:46:53,969 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:46:53,969 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208
2015-07-27 13:47:11,331 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:418 INFO     Ran azure storage account create --affinity-group=perfkita9452a02de3514208 --type=LRS perfkita9452a02de3514208. Got return code (1).
STDOUT: info:    Executing command storage account create
info:    Creating storage account
info:    Error information has been recorded to /root/.azure/azure.err

STDERR: error:   The subscription policy limit for resource type 'storage account count' was exceeded. The limit for resource type 'storage account count' is 100 per subscription, the current count is 100, and the requested increment is 1.
error:   storage account create command failed


2015-07-27 13:47:11,333 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:47:11,333 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure storage account show --json perfkita9452a02de3514208
2015-07-27 13:47:14,194 a9452a02 Thread-1 object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure storage account show --json perfkita9452a02de3514208. Got return code (1).
STDOUT: 
STDERR: The storage account 'perfkita9452a02de3514208' was not found.
Error information has been recorded to /root/.azure/azure.err
storage account show command failed


2015-07-27 13:47:14,235 a9452a02 MainThread object_storage_service(1/1) pkb.py:317 ERROR    Error during benchmark object_storage_service
Traceback (most recent call last):
  File "/home/final/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 290, in RunBenchmark
    DoPreparePhase(benchmark, benchmark_name, spec, detailed_timer)
  File "/home/final/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 200, in DoPreparePhase
    spec.Prepare()
  File "/home/final/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 215, in Prepare
    vm_util.RunThreaded(self.PrepareNetwork, prepare_args)
  File "/home/final/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 292, in RunThreaded
    '\n'.join([stacktrace for stacktrace in exceptions]))
ThreadException: The following exceptions occurred during threaded execution: Traceback (most recent call last):
  File "/home/final/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 276, in RunThreaded
    thread.join(1000)  # Set timeout so that join is interruptable.
  File "/home/final/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 216, in join
    raise errors.VmUtil.ThreadException(self.exception)
ThreadException: Exception occured in thread 139979427034880:
Traceback (most recent call last):
  File "/home/final/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 203, in run
    self.RunWithExceptions()
  File "/home/final/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 210, in RunWithExceptions
    super(ThreadWithExceptions, self).run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/final/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 248, in PrepareNetwork
    network.Create()
  File "/home/final/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 354, in WrappedFunction
    raise e
RetryableCreationError: Creation of AzureStorageAccount failed.


2015-07-27 13:47:14,236 a9452a02 Thread-66 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:47:14,237 a9452a02 Thread-66 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure vm delete --quiet pkb-a9452a02-0
2015-07-27 13:47:21,034 a9452a02 Thread-66 object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure vm delete --quiet pkb-a9452a02-0. Got return code (0).
STDOUT: info:    Executing command vm delete
info:    Getting virtual machines
warn:    No VMs found
info:    vm delete command OK

STDERR: 
2015-07-27 13:47:21,035 a9452a02 Thread-66 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:47:21,035 a9452a02 Thread-66 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure vm show --json pkb-a9452a02-0
2015-07-27 13:47:26,953 a9452a02 Thread-66 object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure vm show --json pkb-a9452a02-0. Got return code (0).
STDOUT: No VMs found

STDERR: 
2015-07-27 13:47:26,954 a9452a02 Thread-66 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:47:26,954 a9452a02 Thread-66 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure service delete --quiet pkb-a9452a02-0
2015-07-27 13:47:29,613 a9452a02 Thread-66 object_storage_service(1/1) vm_util.py:418 INFO     Ran azure service delete --quiet pkb-a9452a02-0. Got return code (1).
STDOUT: info:    Executing command service delete
info:    Deleting cloud service
info:    Error information has been recorded to /root/.azure/azure.err

STDERR: error:   The hosted service does not exist.
error:   service delete command failed


2015-07-27 13:47:29,613 a9452a02 Thread-66 object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:47:29,613 a9452a02 Thread-66 object_storage_service(1/1) vm_util.py:392 INFO     Running: azure service show --json pkb-a9452a02-0
2015-07-27 13:47:32,822 a9452a02 Thread-66 object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure service show --json pkb-a9452a02-0. Got return code (1).
STDOUT: 
STDERR: The hosted service does not exist.
Error information has been recorded to /root/.azure/azure.err
service show command failed


2015-07-27 13:47:32,845 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:47:32,845 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet delete --quiet perfkita9452a02de3514208
2015-07-27 13:47:35,916 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet delete --quiet perfkita9452a02de3514208. Got return code (0).
STDOUT: info:    Executing command network vnet delete
info:    Looking up network configuration
info:    network vnet delete command OK

STDERR: error:   A virtual network with name "perfkita9452a02de3514208" not found

2015-07-27 13:47:35,916 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:47:35,916 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet show --json perfkita9452a02de3514208
2015-07-27 13:47:39,179 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet show --json perfkita9452a02de3514208. Got return code (0).
STDOUT: {}

STDERR: 
2015-07-27 13:47:39,180 a9452a02 MainThread object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _DeleteResource: Deletion of AzureVirtualNetwork failed.
2015-07-27 13:48:08,339 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:48:08,339 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet delete --quiet perfkita9452a02de3514208
2015-07-27 13:48:11,583 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet delete --quiet perfkita9452a02de3514208. Got return code (0).
STDOUT: info:    Executing command network vnet delete
info:    Looking up network configuration
info:    network vnet delete command OK

STDERR: error:   A virtual network with name "perfkita9452a02de3514208" not found

2015-07-27 13:48:11,584 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:48:11,584 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet show --json perfkita9452a02de3514208
2015-07-27 13:48:14,816 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet show --json perfkita9452a02de3514208. Got return code (0).
STDOUT: {}

STDERR: 
2015-07-27 13:48:14,817 a9452a02 MainThread object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _DeleteResource: Deletion of AzureVirtualNetwork failed.
2015-07-27 13:48:34,807 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:48:34,808 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet delete --quiet perfkita9452a02de3514208
2015-07-27 13:48:37,845 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet delete --quiet perfkita9452a02de3514208. Got return code (0).
STDOUT: info:    Executing command network vnet delete
info:    Looking up network configuration
info:    network vnet delete command OK

STDERR: error:   A virtual network with name "perfkita9452a02de3514208" not found

2015-07-27 13:48:37,845 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:48:37,845 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet show --json perfkita9452a02de3514208
2015-07-27 13:48:41,157 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet show --json perfkita9452a02de3514208. Got return code (0).
STDOUT: {}

STDERR: 
2015-07-27 13:48:41,157 a9452a02 MainThread object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _DeleteResource: Deletion of AzureVirtualNetwork failed.
2015-07-27 13:49:10,367 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:49:10,367 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet delete --quiet perfkita9452a02de3514208
2015-07-27 13:49:13,602 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet delete --quiet perfkita9452a02de3514208. Got return code (0).
STDOUT: info:    Executing command network vnet delete
info:    Looking up network configuration
info:    network vnet delete command OK

STDERR: error:   A virtual network with name "perfkita9452a02de3514208" not found

2015-07-27 13:49:13,602 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:49:13,602 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet show --json perfkita9452a02de3514208
2015-07-27 13:49:17,091 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet show --json perfkita9452a02de3514208. Got return code (0).
STDOUT: {}

STDERR: 
2015-07-27 13:49:17,092 a9452a02 MainThread object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _DeleteResource: Deletion of AzureVirtualNetwork failed.
2015-07-27 13:49:35,365 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:49:35,366 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet delete --quiet perfkita9452a02de3514208
2015-07-27 13:49:38,760 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet delete --quiet perfkita9452a02de3514208. Got return code (0).
STDOUT: info:    Executing command network vnet delete
info:    Looking up network configuration
info:    network vnet delete command OK

STDERR: error:   A virtual network with name "perfkita9452a02de3514208" not found

2015-07-27 13:49:38,760 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:49:38,760 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet show --json perfkita9452a02de3514208
2015-07-27 13:49:41,890 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet show --json perfkita9452a02de3514208. Got return code (0).
STDOUT: {}

STDERR: 
2015-07-27 13:49:41,890 a9452a02 MainThread object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _DeleteResource: Deletion of AzureVirtualNetwork failed.
2015-07-27 13:50:04,248 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:50:04,248 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet delete --quiet perfkita9452a02de3514208
2015-07-27 13:50:07,502 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet delete --quiet perfkita9452a02de3514208. Got return code (0).
STDOUT: info:    Executing command network vnet delete
info:    Looking up network configuration
info:    network vnet delete command OK

STDERR: error:   A virtual network with name "perfkita9452a02de3514208" not found

2015-07-27 13:50:07,502 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:50:07,503 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet show --json perfkita9452a02de3514208
2015-07-27 13:50:10,634 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet show --json perfkita9452a02de3514208. Got return code (0).
STDOUT: {}

STDERR: 
2015-07-27 13:50:10,634 a9452a02 MainThread object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _DeleteResource: Deletion of AzureVirtualNetwork failed.
2015-07-27 13:50:34,627 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:50:34,627 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet delete --quiet perfkita9452a02de3514208
2015-07-27 13:50:37,745 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet delete --quiet perfkita9452a02de3514208. Got return code (0).
STDOUT: info:    Executing command network vnet delete
info:    Looking up network configuration
info:    network vnet delete command OK

STDERR: error:   A virtual network with name "perfkita9452a02de3514208" not found

2015-07-27 13:50:37,745 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:50:37,745 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet show --json perfkita9452a02de3514208
2015-07-27 13:50:41,370 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet show --json perfkita9452a02de3514208. Got return code (0).
STDOUT: {}

STDERR: 
2015-07-27 13:50:41,370 a9452a02 MainThread object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _DeleteResource: Deletion of AzureVirtualNetwork failed.
2015-07-27 13:51:09,909 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:51:09,910 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet delete --quiet perfkita9452a02de3514208
2015-07-27 13:51:13,288 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet delete --quiet perfkita9452a02de3514208. Got return code (0).
STDOUT: info:    Executing command network vnet delete
info:    Looking up network configuration
info:    network vnet delete command OK

STDERR: error:   A virtual network with name "perfkita9452a02de3514208" not found

2015-07-27 13:51:13,289 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:51:13,289 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet show --json perfkita9452a02de3514208
2015-07-27 13:51:16,857 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet show --json perfkita9452a02de3514208. Got return code (0).
STDOUT: {}

STDERR: 
2015-07-27 13:51:16,857 a9452a02 MainThread object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _DeleteResource: Deletion of AzureVirtualNetwork failed.
2015-07-27 13:51:32,493 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:51:32,493 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet delete --quiet perfkita9452a02de3514208
2015-07-27 13:51:35,525 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet delete --quiet perfkita9452a02de3514208. Got return code (0).
STDOUT: info:    Executing command network vnet delete
info:    Looking up network configuration
info:    network vnet delete command OK

STDERR: error:   A virtual network with name "perfkita9452a02de3514208" not found

2015-07-27 13:51:35,526 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:51:35,526 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet show --json perfkita9452a02de3514208
2015-07-27 13:51:39,317 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet show --json perfkita9452a02de3514208. Got return code (0).
STDOUT: {}

STDERR: 
2015-07-27 13:51:39,317 a9452a02 MainThread object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _DeleteResource: Deletion of AzureVirtualNetwork failed.
2015-07-27 13:52:03,718 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:52:03,719 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet delete --quiet perfkita9452a02de3514208
2015-07-27 13:52:07,020 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet delete --quiet perfkita9452a02de3514208. Got return code (0).
STDOUT: info:    Executing command network vnet delete
info:    Looking up network configuration
info:    network vnet delete command OK

STDERR: error:   A virtual network with name "perfkita9452a02de3514208" not found

2015-07-27 13:52:07,020 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:52:07,020 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet show --json perfkita9452a02de3514208
2015-07-27 13:52:10,208 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet show --json perfkita9452a02de3514208. Got return code (0).
STDOUT: {}

STDERR: 
2015-07-27 13:52:10,208 a9452a02 MainThread object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _DeleteResource: Deletion of AzureVirtualNetwork failed.
2015-07-27 13:52:34,490 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:52:34,490 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet delete --quiet perfkita9452a02de3514208
2015-07-27 13:52:37,312 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet delete --quiet perfkita9452a02de3514208. Got return code (0).
STDOUT: info:    Executing command network vnet delete
info:    Looking up network configuration
info:    network vnet delete command OK

STDERR: error:   A virtual network with name "perfkita9452a02de3514208" not found

2015-07-27 13:52:37,312 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:52:37,312 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet show --json perfkita9452a02de3514208
2015-07-27 13:52:40,622 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet show --json perfkita9452a02de3514208. Got return code (0).
STDOUT: {}

STDERR: 
2015-07-27 13:52:40,623 a9452a02 MainThread object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _DeleteResource: Deletion of AzureVirtualNetwork failed.
2015-07-27 13:52:59,114 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:52:59,114 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet delete --quiet perfkita9452a02de3514208
2015-07-27 13:53:02,120 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet delete --quiet perfkita9452a02de3514208. Got return code (0).
STDOUT: info:    Executing command network vnet delete
info:    Looking up network configuration
info:    network vnet delete command OK

STDERR: error:   A virtual network with name "perfkita9452a02de3514208" not found

2015-07-27 13:53:02,121 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:53:02,121 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet show --json perfkita9452a02de3514208
2015-07-27 13:53:05,879 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet show --json perfkita9452a02de3514208. Got return code (0).
STDOUT: {}

STDERR: 
2015-07-27 13:53:05,880 a9452a02 MainThread object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _DeleteResource: Deletion of AzureVirtualNetwork failed.
2015-07-27 13:53:32,972 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:53:32,972 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet delete --quiet perfkita9452a02de3514208
2015-07-27 13:53:36,118 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet delete --quiet perfkita9452a02de3514208. Got return code (0).
STDOUT: info:    Executing command network vnet delete
info:    Looking up network configuration
info:    network vnet delete command OK

STDERR: error:   A virtual network with name "perfkita9452a02de3514208" not found

2015-07-27 13:53:36,118 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:53:36,119 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet show --json perfkita9452a02de3514208
2015-07-27 13:53:39,341 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet show --json perfkita9452a02de3514208. Got return code (0).
STDOUT: {}

STDERR: 
2015-07-27 13:53:39,341 a9452a02 MainThread object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _DeleteResource: Deletion of AzureVirtualNetwork failed.
2015-07-27 13:54:02,967 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:54:02,967 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet delete --quiet perfkita9452a02de3514208
2015-07-27 13:54:06,638 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet delete --quiet perfkita9452a02de3514208. Got return code (0).
STDOUT: info:    Executing command network vnet delete
info:    Looking up network configuration
info:    network vnet delete command OK

STDERR: error:   A virtual network with name "perfkita9452a02de3514208" not found

2015-07-27 13:54:06,638 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:54:06,638 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet show --json perfkita9452a02de3514208
2015-07-27 13:54:09,755 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet show --json perfkita9452a02de3514208. Got return code (0).
STDOUT: {}

STDERR: 
2015-07-27 13:54:09,756 a9452a02 MainThread object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _DeleteResource: Deletion of AzureVirtualNetwork failed.
2015-07-27 13:54:32,942 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:54:32,943 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet delete --quiet perfkita9452a02de3514208
2015-07-27 13:54:35,861 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet delete --quiet perfkita9452a02de3514208. Got return code (0).
STDOUT: info:    Executing command network vnet delete
info:    Looking up network configuration
info:    network vnet delete command OK

STDERR: error:   A virtual network with name "perfkita9452a02de3514208" not found

2015-07-27 13:54:35,861 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:54:35,861 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet show --json perfkita9452a02de3514208
2015-07-27 13:54:39,524 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet show --json perfkita9452a02de3514208. Got return code (0).
STDOUT: {}

STDERR: 
2015-07-27 13:54:39,525 a9452a02 MainThread object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _DeleteResource: Deletion of AzureVirtualNetwork failed.
2015-07-27 13:55:07,264 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:55:07,264 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet delete --quiet perfkita9452a02de3514208
2015-07-27 13:55:10,534 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet delete --quiet perfkita9452a02de3514208. Got return code (0).
STDOUT: info:    Executing command network vnet delete
info:    Looking up network configuration
info:    network vnet delete command OK

STDERR: error:   A virtual network with name "perfkita9452a02de3514208" not found

2015-07-27 13:55:10,535 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:55:10,535 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet show --json perfkita9452a02de3514208
2015-07-27 13:55:14,769 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet show --json perfkita9452a02de3514208. Got return code (0).
STDOUT: {}

STDERR: 
2015-07-27 13:55:14,769 a9452a02 MainThread object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _DeleteResource: Deletion of AzureVirtualNetwork failed.
2015-07-27 13:55:34,447 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:55:34,447 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet delete --quiet perfkita9452a02de3514208
2015-07-27 13:55:37,349 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet delete --quiet perfkita9452a02de3514208. Got return code (0).
STDOUT: info:    Executing command network vnet delete
info:    Looking up network configuration
info:    network vnet delete command OK

STDERR: error:   A virtual network with name "perfkita9452a02de3514208" not found

2015-07-27 13:55:37,350 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:55:37,350 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet show --json perfkita9452a02de3514208
2015-07-27 13:55:40,553 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet show --json perfkita9452a02de3514208. Got return code (0).
STDOUT: {}

STDERR: 
2015-07-27 13:55:40,553 a9452a02 MainThread object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _DeleteResource: Deletion of AzureVirtualNetwork failed.
2015-07-27 13:56:05,079 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:56:05,079 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet delete --quiet perfkita9452a02de3514208
2015-07-27 13:56:08,103 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet delete --quiet perfkita9452a02de3514208. Got return code (0).
STDOUT: info:    Executing command network vnet delete
info:    Looking up network configuration
info:    network vnet delete command OK

STDERR: error:   A virtual network with name "perfkita9452a02de3514208" not found

2015-07-27 13:56:08,103 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:56:08,103 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet show --json perfkita9452a02de3514208
2015-07-27 13:56:11,297 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet show --json perfkita9452a02de3514208. Got return code (0).
STDOUT: {}

STDERR: 
2015-07-27 13:56:11,297 a9452a02 MainThread object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _DeleteResource: Deletion of AzureVirtualNetwork failed.
2015-07-27 13:56:33,612 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:56:33,612 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet delete --quiet perfkita9452a02de3514208
2015-07-27 13:56:36,640 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet delete --quiet perfkita9452a02de3514208. Got return code (0).
STDOUT: info:    Executing command network vnet delete
info:    Looking up network configuration
info:    network vnet delete command OK

STDERR: error:   A virtual network with name "perfkita9452a02de3514208" not found

2015-07-27 13:56:36,640 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:56:36,640 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet show --json perfkita9452a02de3514208
2015-07-27 13:56:39,877 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet show --json perfkita9452a02de3514208. Got return code (0).
STDOUT: {}

STDERR: 
2015-07-27 13:56:39,877 a9452a02 MainThread object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _DeleteResource: Deletion of AzureVirtualNetwork failed.
2015-07-27 13:57:08,319 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:57:08,320 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet delete --quiet perfkita9452a02de3514208
2015-07-27 13:57:11,909 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet delete --quiet perfkita9452a02de3514208. Got return code (0).
STDOUT: info:    Executing command network vnet delete
info:    Looking up network configuration
info:    network vnet delete command OK

STDERR: error:   A virtual network with name "perfkita9452a02de3514208" not found

2015-07-27 13:57:11,909 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:57:11,910 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet show --json perfkita9452a02de3514208
2015-07-27 13:57:15,303 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet show --json perfkita9452a02de3514208. Got return code (0).
STDOUT: {}

STDERR: 
2015-07-27 13:57:15,304 a9452a02 MainThread object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _DeleteResource: Deletion of AzureVirtualNetwork failed.
2015-07-27 13:57:30,534 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:57:30,534 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet delete --quiet perfkita9452a02de3514208
2015-07-27 13:57:33,917 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet delete --quiet perfkita9452a02de3514208. Got return code (0).
STDOUT: info:    Executing command network vnet delete
info:    Looking up network configuration
info:    network vnet delete command OK

STDERR: error:   A virtual network with name "perfkita9452a02de3514208" not found

2015-07-27 13:57:33,918 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:57:33,918 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet show --json perfkita9452a02de3514208
2015-07-27 13:57:37,760 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet show --json perfkita9452a02de3514208. Got return code (0).
STDOUT: {}

STDERR: 
2015-07-27 13:57:37,760 a9452a02 MainThread object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _DeleteResource: Deletion of AzureVirtualNetwork failed.
2015-07-27 13:57:56,277 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:57:56,277 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet delete --quiet perfkita9452a02de3514208
2015-07-27 13:57:59,684 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet delete --quiet perfkita9452a02de3514208. Got return code (0).
STDOUT: info:    Executing command network vnet delete
info:    Looking up network configuration
info:    network vnet delete command OK

STDERR: error:   A virtual network with name "perfkita9452a02de3514208" not found

2015-07-27 13:57:59,684 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:57:59,684 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet show --json perfkita9452a02de3514208
2015-07-27 13:58:02,974 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet show --json perfkita9452a02de3514208. Got return code (0).
STDOUT: {}

STDERR: 
2015-07-27 13:58:02,974 a9452a02 MainThread object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _DeleteResource: Deletion of AzureVirtualNetwork failed.
2015-07-27 13:58:25,857 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:58:25,857 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet delete --quiet perfkita9452a02de3514208
2015-07-27 13:58:28,890 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet delete --quiet perfkita9452a02de3514208. Got return code (0).
STDOUT: info:    Executing command network vnet delete
info:    Looking up network configuration
info:    network vnet delete command OK

STDERR: error:   A virtual network with name "perfkita9452a02de3514208" not found

2015-07-27 13:58:28,890 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:58:28,890 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet show --json perfkita9452a02de3514208
2015-07-27 13:58:32,581 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet show --json perfkita9452a02de3514208. Got return code (0).
STDOUT: {}

STDERR: 
2015-07-27 13:58:32,582 a9452a02 MainThread object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _DeleteResource: Deletion of AzureVirtualNetwork failed.
2015-07-27 13:58:55,458 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:58:55,458 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet delete --quiet perfkita9452a02de3514208
2015-07-27 13:58:58,471 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet delete --quiet perfkita9452a02de3514208. Got return code (0).
STDOUT: info:    Executing command network vnet delete
info:    Looking up network configuration
info:    network vnet delete command OK

STDERR: error:   A virtual network with name "perfkita9452a02de3514208" not found

2015-07-27 13:58:58,472 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:58:58,472 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet show --json perfkita9452a02de3514208
2015-07-27 13:59:01,642 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet show --json perfkita9452a02de3514208. Got return code (0).
STDOUT: {}

STDERR: 
2015-07-27 13:59:01,642 a9452a02 MainThread object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _DeleteResource: Deletion of AzureVirtualNetwork failed.
2015-07-27 13:59:25,260 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:59:25,260 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet delete --quiet perfkita9452a02de3514208
2015-07-27 13:59:29,188 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet delete --quiet perfkita9452a02de3514208. Got return code (0).
STDOUT: info:    Executing command network vnet delete
info:    Looking up network configuration
info:    network vnet delete command OK

STDERR: error:   A virtual network with name "perfkita9452a02de3514208" not found

2015-07-27 13:59:29,188 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:59:29,188 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet show --json perfkita9452a02de3514208
2015-07-27 13:59:32,265 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet show --json perfkita9452a02de3514208. Got return code (0).
STDOUT: {}

STDERR: 
2015-07-27 13:59:32,265 a9452a02 MainThread object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _DeleteResource: Deletion of AzureVirtualNetwork failed.
2015-07-27 13:59:49,241 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:59:49,241 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet delete --quiet perfkita9452a02de3514208
2015-07-27 13:59:52,530 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet delete --quiet perfkita9452a02de3514208. Got return code (0).
STDOUT: info:    Executing command network vnet delete
info:    Looking up network configuration
info:    network vnet delete command OK

STDERR: error:   A virtual network with name "perfkita9452a02de3514208" not found

2015-07-27 13:59:52,530 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 13:59:52,531 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet show --json perfkita9452a02de3514208
2015-07-27 13:59:55,760 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet show --json perfkita9452a02de3514208. Got return code (0).
STDOUT: {}

STDERR: 
2015-07-27 13:59:55,760 a9452a02 MainThread object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _DeleteResource: Deletion of AzureVirtualNetwork failed.
2015-07-27 14:00:18,831 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 14:00:18,831 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet delete --quiet perfkita9452a02de3514208
2015-07-27 14:00:22,209 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet delete --quiet perfkita9452a02de3514208. Got return code (0).
STDOUT: info:    Executing command network vnet delete
info:    Looking up network configuration
info:    network vnet delete command OK

STDERR: error:   A virtual network with name "perfkita9452a02de3514208" not found

2015-07-27 14:00:22,209 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 14:00:22,210 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet show --json perfkita9452a02de3514208
2015-07-27 14:00:25,691 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet show --json perfkita9452a02de3514208. Got return code (0).
STDOUT: {}

STDERR: 
2015-07-27 14:00:25,692 a9452a02 MainThread object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _DeleteResource: Deletion of AzureVirtualNetwork failed.
2015-07-27 14:00:54,187 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 14:00:54,187 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet delete --quiet perfkita9452a02de3514208
2015-07-27 14:00:58,191 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet delete --quiet perfkita9452a02de3514208. Got return code (0).
STDOUT: info:    Executing command network vnet delete
info:    Looking up network configuration
info:    network vnet delete command OK

STDERR: error:   A virtual network with name "perfkita9452a02de3514208" not found

2015-07-27 14:00:58,191 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 14:00:58,191 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet show --json perfkita9452a02de3514208
2015-07-27 14:01:01,778 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet show --json perfkita9452a02de3514208. Got return code (0).
STDOUT: {}

STDERR: 
2015-07-27 14:01:01,779 a9452a02 MainThread object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _DeleteResource: Deletion of AzureVirtualNetwork failed.
2015-07-27 14:01:25,612 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 14:01:25,613 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet delete --quiet perfkita9452a02de3514208
2015-07-27 14:01:29,328 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet delete --quiet perfkita9452a02de3514208. Got return code (0).
STDOUT: info:    Executing command network vnet delete
info:    Looking up network configuration
info:    network vnet delete command OK

STDERR: error:   A virtual network with name "perfkita9452a02de3514208" not found

2015-07-27 14:01:29,328 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 14:01:29,328 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet show --json perfkita9452a02de3514208
2015-07-27 14:01:33,420 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet show --json perfkita9452a02de3514208. Got return code (0).
STDOUT: {}

STDERR: 
2015-07-27 14:01:33,421 a9452a02 MainThread object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _DeleteResource: Deletion of AzureVirtualNetwork failed.
2015-07-27 14:01:53,369 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 14:01:53,370 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet delete --quiet perfkita9452a02de3514208
2015-07-27 14:01:56,733 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet delete --quiet perfkita9452a02de3514208. Got return code (0).
STDOUT: info:    Executing command network vnet delete
info:    Looking up network configuration
info:    network vnet delete command OK

STDERR: error:   A virtual network with name "perfkita9452a02de3514208" not found

2015-07-27 14:01:56,733 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 14:01:56,733 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet show --json perfkita9452a02de3514208
2015-07-27 14:02:00,476 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet show --json perfkita9452a02de3514208. Got return code (0).
STDOUT: {}

STDERR: 
2015-07-27 14:02:00,477 a9452a02 MainThread object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _DeleteResource: Deletion of AzureVirtualNetwork failed.
2015-07-27 14:02:18,145 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 14:02:18,145 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet delete --quiet perfkita9452a02de3514208
2015-07-27 14:02:21,473 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet delete --quiet perfkita9452a02de3514208. Got return code (0).
STDOUT: info:    Executing command network vnet delete
info:    Looking up network configuration
info:    network vnet delete command OK

STDERR: error:   A virtual network with name "perfkita9452a02de3514208" not found

2015-07-27 14:02:21,473 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 14:02:21,473 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet show --json perfkita9452a02de3514208
2015-07-27 14:02:24,741 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet show --json perfkita9452a02de3514208. Got return code (0).
STDOUT: {}

STDERR: 
2015-07-27 14:02:24,741 a9452a02 MainThread object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _DeleteResource: Deletion of AzureVirtualNetwork failed.
2015-07-27 14:02:43,072 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 14:02:43,073 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet delete --quiet perfkita9452a02de3514208
2015-07-27 14:02:46,657 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet delete --quiet perfkita9452a02de3514208. Got return code (0).
STDOUT: info:    Executing command network vnet delete
info:    Looking up network configuration
info:    network vnet delete command OK

STDERR: error:   A virtual network with name "perfkita9452a02de3514208" not found

2015-07-27 14:02:46,657 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 14:02:46,657 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet show --json perfkita9452a02de3514208
2015-07-27 14:02:50,392 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet show --json perfkita9452a02de3514208. Got return code (0).
STDOUT: {}

STDERR: 
2015-07-27 14:02:50,392 a9452a02 MainThread object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _DeleteResource: Deletion of AzureVirtualNetwork failed.
2015-07-27 14:03:15,499 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 14:03:15,499 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet delete --quiet perfkita9452a02de3514208
2015-07-27 14:03:18,784 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet delete --quiet perfkita9452a02de3514208. Got return code (0).
STDOUT: info:    Executing command network vnet delete
info:    Looking up network configuration
info:    network vnet delete command OK

STDERR: error:   A virtual network with name "perfkita9452a02de3514208" not found

2015-07-27 14:03:18,785 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 14:03:18,785 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet show --json perfkita9452a02de3514208
2015-07-27 14:03:21,957 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet show --json perfkita9452a02de3514208. Got return code (0).
STDOUT: {}

STDERR: 
2015-07-27 14:03:21,957 a9452a02 MainThread object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _DeleteResource: Deletion of AzureVirtualNetwork failed.
2015-07-27 14:03:50,463 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 14:03:50,463 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet delete --quiet perfkita9452a02de3514208
2015-07-27 14:03:53,806 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet delete --quiet perfkita9452a02de3514208. Got return code (0).
STDOUT: info:    Executing command network vnet delete
info:    Looking up network configuration
info:    network vnet delete command OK

STDERR: error:   A virtual network with name "perfkita9452a02de3514208" not found

2015-07-27 14:03:53,806 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 14:03:53,806 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet show --json perfkita9452a02de3514208
2015-07-27 14:03:57,009 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet show --json perfkita9452a02de3514208. Got return code (0).
STDOUT: {}

STDERR: 
2015-07-27 14:03:57,010 a9452a02 MainThread object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _DeleteResource: Deletion of AzureVirtualNetwork failed.
2015-07-27 14:04:24,270 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 14:04:24,270 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet delete --quiet perfkita9452a02de3514208
2015-07-27 14:04:27,267 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet delete --quiet perfkita9452a02de3514208. Got return code (0).
STDOUT: info:    Executing command network vnet delete
info:    Looking up network configuration
info:    network vnet delete command OK

STDERR: error:   A virtual network with name "perfkita9452a02de3514208" not found

2015-07-27 14:04:27,268 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 14:04:27,268 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet show --json perfkita9452a02de3514208
2015-07-27 14:04:30,663 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet show --json perfkita9452a02de3514208. Got return code (0).
STDOUT: {}

STDERR: 
2015-07-27 14:04:30,663 a9452a02 MainThread object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _DeleteResource: Deletion of AzureVirtualNetwork failed.
2015-07-27 14:04:57,099 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 14:04:57,100 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet delete --quiet perfkita9452a02de3514208
2015-07-27 14:05:00,527 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet delete --quiet perfkita9452a02de3514208. Got return code (0).
STDOUT: info:    Executing command network vnet delete
info:    Looking up network configuration
info:    network vnet delete command OK

STDERR: error:   A virtual network with name "perfkita9452a02de3514208" not found

2015-07-27 14:05:00,527 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 14:05:00,527 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet show --json perfkita9452a02de3514208
2015-07-27 14:05:03,966 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet show --json perfkita9452a02de3514208. Got return code (0).
STDOUT: {}

STDERR: 
2015-07-27 14:05:03,967 a9452a02 MainThread object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _DeleteResource: Deletion of AzureVirtualNetwork failed.
2015-07-27 14:05:33,038 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 14:05:33,039 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet delete --quiet perfkita9452a02de3514208
2015-07-27 14:05:36,245 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet delete --quiet perfkita9452a02de3514208. Got return code (0).
STDOUT: info:    Executing command network vnet delete
info:    Looking up network configuration
info:    network vnet delete command OK

STDERR: error:   A virtual network with name "perfkita9452a02de3514208" not found

2015-07-27 14:05:36,245 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 14:05:36,245 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet show --json perfkita9452a02de3514208
2015-07-27 14:05:39,671 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet show --json perfkita9452a02de3514208. Got return code (0).
STDOUT: {}

STDERR: 
2015-07-27 14:05:39,671 a9452a02 MainThread object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _DeleteResource: Deletion of AzureVirtualNetwork failed.
2015-07-27 14:06:01,926 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 14:06:01,926 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet delete --quiet perfkita9452a02de3514208
2015-07-27 14:06:05,101 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet delete --quiet perfkita9452a02de3514208. Got return code (0).
STDOUT: info:    Executing command network vnet delete
info:    Looking up network configuration
info:    network vnet delete command OK

STDERR: error:   A virtual network with name "perfkita9452a02de3514208" not found

2015-07-27 14:06:05,102 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 14:06:05,102 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet show --json perfkita9452a02de3514208
2015-07-27 14:06:08,478 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet show --json perfkita9452a02de3514208. Got return code (0).
STDOUT: {}

STDERR: 
2015-07-27 14:06:08,479 a9452a02 MainThread object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _DeleteResource: Deletion of AzureVirtualNetwork failed.
2015-07-27 14:06:31,307 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 14:06:31,307 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet delete --quiet perfkita9452a02de3514208
2015-07-27 14:06:34,614 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet delete --quiet perfkita9452a02de3514208. Got return code (0).
STDOUT: info:    Executing command network vnet delete
info:    Looking up network configuration
info:    network vnet delete command OK

STDERR: error:   A virtual network with name "perfkita9452a02de3514208" not found

2015-07-27 14:06:34,614 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 14:06:34,614 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet show --json perfkita9452a02de3514208
2015-07-27 14:06:37,767 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet show --json perfkita9452a02de3514208. Got return code (0).
STDOUT: {}

STDERR: 
2015-07-27 14:06:37,768 a9452a02 MainThread object_storage_service(1/1) vm_util.py:357 ERROR    Got exception running _DeleteResource: Deletion of AzureVirtualNetwork failed.
2015-07-27 14:07:05,770 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 14:07:05,770 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet delete --quiet perfkita9452a02de3514208
2015-07-27 14:07:08,924 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet delete --quiet perfkita9452a02de3514208. Got return code (0).
STDOUT: info:    Executing command network vnet delete
info:    Looking up network configuration
info:    network vnet delete command OK

STDERR: error:   A virtual network with name "perfkita9452a02de3514208" not found

2015-07-27 14:07:08,924 a9452a02 MainThread object_storage_service(1/1) vm_util.py:389 DEBUG    Environment variables: None
2015-07-27 14:07:08,924 a9452a02 MainThread object_storage_service(1/1) vm_util.py:392 INFO     Running: azure network vnet show --json perfkita9452a02de3514208
2015-07-27 14:07:12,737 a9452a02 MainThread object_storage_service(1/1) vm_util.py:420 DEBUG    Ran azure network vnet show --json perfkita9452a02de3514208. Got return code (0).
STDOUT: {}

STDERR: 
2015-07-27 14:07:12,737 a9452a02 MainThread object_storage_service(1/1) benchmark_spec.py:242 ERROR    Got an exception deleting networks. Attempting to continue tearing down.
Traceback (most recent call last):
  File "/home/final/PerfKitBenchmarker/perfkitbenchmarker/benchmark_spec.py", line 240, in Delete
    net.Delete()
  File "/home/final/PerfKitBenchmarker/perfkitbenchmarker/azure/azure_network.py", line 228, in Delete
    self.vnet.Delete()
  File "/home/final/PerfKitBenchmarker/perfkitbenchmarker/resource.py", line 135, in Delete
    self._DeleteResource()
  File "/home/final/PerfKitBenchmarker/perfkitbenchmarker/vm_util.py", line 354, in WrappedFunction
    raise e
RetryableDeletionError: Deletion of AzureVirtualNetwork failed.
2015-07-27 14:07:12,740 a9452a02 MainThread object_storage_service(1/1) pkb.py:426 INFO     Complete logs can be found at: /tmp/perfkitbenchmarker/run_a9452a02/pkb.log
